# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lZCfsxXAURaANGIfdvIggD7n9W2SlVmy
"""

import pandas as pd

df = pd.read_csv('data.csv')

print(df.head())

# حذف الصفوف المكررة
df = df.drop_duplicates()

# وهاذي حذف الصفوف الفارغة كلها
df = df.dropna(how='all')

# من اجل تبديل القيم الفارغة والمفقودة في أعمدة لولة والثانية لانها
df['عمود1'] = df['عمود1'].fillna(df['عمود1'].mean())
df['عمود2'] = df['عمود2'].fillna('غير معروف')

df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

df['الاسم'] = df['الاسم'].str.lower()

df['التاريخ'] = pd.to_datetime(df['التاريخ'], errors='coerce')

df.to_csv('cleaned_data.csv', index=False)

print("   cleaned_data.csv")