# -*- coding: utf-8 -*-
"""bigdata(salles Analytics).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDMz_eRCV8nct_Uzd11093KNvflfhJwy
"""



"""Creating a simple dataset."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile sales.txt
# # Product,Quantity,Price,Region
# Apple,3,2.5,North
# Banana,6,1.2,South
# Apple,1,2.5,East
# Orange,4,1.8,North
# Banana,2,1.2,South
# Apple,5,2.5,West
# Orange,3,1.8,East
# Apple,4,2.6,North
# Banana,8,1.1,East
# Apple,7,2.5,South
# Orange,5,1.9,West
# Banana,3,1.3,North
# Grapes,10,3.2,East
# Grapes,5,3.2,South
# Banana,9,1.2,West
# Apple,6,2.4,East
# Orange,4,1.8,South
# Grapes,8,3.3,North
# Apple,2,2.5,North
# Banana,5,1.2,East
# Grapes,12,3.1,West
# Apple,9,2.5,West
# Orange,7,1.7,South
# Grapes,6,3.2,East
# Banana,11,1.1,South
# Apple,10,2.6,North
# Orange,2,1.9,West
# Grapes,9,3.0,North
# Apple,3,2.4,East
# Banana,7,1.3,West
# Apple,8,2.5,South
# Orange,5,1.8,North
# Grapes,10,3.2,West
# Apple,4,2.5,East
# Banana,6,1.2,North
# Orange,9,1.9,East
# Apple,7,2.6,South
# Grapes,5,3.3,West
# Banana,12,1.1,South
# Apple,2,2.5,North
# Orange,8,1.8,West
# Grapes,7,3.1,East
# Apple,11,2.4,East
# Banana,5,1.2,West
# Orange,3,1.9,North
# Grapes,4,3.2,South
# Apple,9,2.6,North
# Banana,10,1.2,East
# Grapes,8,3.1,West
# Apple,5,2.5,South
# Orange,7,1.7,East
# Grapes,6,3.0,North
# Banana,8,1.2,South
# Apple,4,2.4,West
# Orange,9,1.8,North
# Grapes,5,3.3,East
# Banana,11,1.1,West
# Apple,3,2.5,South
# Orange,2,1.9,South
# Grapes,9,3.0,East
# Apple,8,2.6,North
# Banana,6,1.2,East
# Orange,4,1.8,West
# Grapes,10,3.2,South
# Apple,12,2.4,East
# Banana,9,1.1,North
# Orange,3,1.9,East
# Grapes,11,3.1,West
# Apple,7,2.5,South
# Banana,5,1.3,West
# Orange,6,1.8,North
# Grapes,8,3.2,East
#

"""Implement the Mapper"""

def mapper(line):
    fields = line.strip().split(',')
    if len(fields) != 4 or fields[0].startswith("#"):
        return []
    product, qty, price, region = fields
    qty = float(qty)
    price = float(price)
    revenue = qty * price
    return [((product, region), revenue)]

"""Shuffle Phase"""

from collections import defaultdict

def shuffle(mapped_data):
    grouped = defaultdict(list)
    for key, value in mapped_data:
        grouped[key].append(value)
    return grouped

"""Reducer Phase"""

from collections import defaultdict

def reducer(mapped_data):
    grouped = defaultdict(float)
    for key, value in mapped_data:
        grouped[key] += value
    return grouped

"""Combine the Phases"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile sales.txt
# # Product,Quantity,Price,Region
# Apple,3,2.5,North
# Banana,6,1.2,South
# Apple,1,2.5,East
# Orange,4,1.8,North
# Banana,2,1.2,South
# Apple,5,2.5,West
# Orange,3,1.8,East
# Apple,4,2.6,North
# Banana,8,1.1,East
# Apple,7,2.5,South
# Orange,5,1.9,West
# Banana,3,1.3,North
# Grapes,10,3.2,East
# Grapes,5,3.2,South
# Banana,9,1.2,West
# Apple,6,2.4,East
# Orange,4,1.8,South
# Grapes,8,3.3,North
# Apple,2,2.5,North
# Banana,5,1.2,East
# Grapes,12,3.1,West
# Apple,9,2.5,West
# Orange,7,1.7,South
# Grapes,6,3.2,East
# Banana,11,1.1,South
# Apple,10,2.6,North
# Orange,2,1.9,West
# Grapes,9,3.0,North
# Apple,3,2.4,East
# Banana,7,1.3,West
# Apple,8,2.5,South
# Orange,5,1.8,North
# Grapes,10,3.2,West
# Apple,4,2.5,East
# Banana,6,1.2,North
# Orange,9,1.9,East
# Apple,7,2.6,South
# Grapes,5,3.3,West
# Banana,12,1.1,South
# Apple,2,2.5,North
# Orange,8,1.8,West
# Grapes,7,3.1,East
# Apple,11,2.4,East
# Banana,5,1.2,West
# Orange,3,1.9,North
# Grapes,4,3.2,South
# Apple,9,2.6,North
# Banana,10,1.2,East
# Grapes,8,3.1,West
# Apple,5,2.5,South
# Orange,7,1.7,East
# Grapes,6,3.0,North
# Banana,8,1.2,South
# Apple,4,2.4,West
# Orange,9,1.8,North
# Grapes,5,3.3,East
# Banana,11,1.1,West
# Apple,3,2.5,South
# Orange,2,1.9,South
# Grapes,9,3.0,East
# Apple,8,2.6,North
# Banana,6,1.2,East
# Orange,4,1.8,West
# Grapes,10,3.2,South
# Apple,12,2.4,East
# Banana,9,1.1,North
# Orange,3,1.9,East
# Grapes,11,3.1,West
# Apple,7,2.5,South
# Banana,5,1.3,West
# Orange,6,1.8,North
# Grapes,8,3.2,East
#

"""**mapper**"""

def mapper(line):
    fields = line.strip().split(',')
    if len(fields) != 4 or fields[0].startswith("#"):
        return []
    product, qty, price, region = fields
    qty = float(qty)
    price = float(price)
    revenue = qty * price
    return [((product, region), revenue)]

print(mapper("Apple,3,2.5,North"))

"""**reducer**"""

from collections import defaultdict

def reducer(mapped_data):
    grouped = defaultdict(float)
    for key, value in mapped_data:
        grouped[key] += value
    return grouped

mapped = []
with open("sales.txt", "r") as f:
    for line in f:
        mapped.extend(mapper(line))

reduced = reducer(mapped)

# Display results nicely
for (product, region), total in sorted(reduced.items()):
    print(f"{product:10s} | {region:6s} | {total:8.2f}")